import { type Metadata } from "next";
import { type ReactNode } from "react";
import { GeistSans } from "geist/font/sans";

import "~/styles/globals.css";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: ReactNode }>) {
  const locale = "en-US";

  return (
    <html lang={locale} className={`${GeistSans.variable}`}>
      <body>{children}</body>
    </html>
  );
}
